### ISSUE TITLE
清华网盘下载

### ISSUE THREAD

**Issue by ForrestPi** [gerwang/CudaFaceTracking#1]
你好  请问清华网盘内容可以放置在百度网盘 或者 googleDrive 吗?
清华网盘内容无法一次性下载下载下来

**Comment by gerwang** [comment]
制作了一个压缩包下载链接
https://cloud.tsinghua.edu.cn/f/84ffbe5ffd994cfeabfc/
密码CudaFaceTracking

**Comment by ForrestPi** [comment]
@gerwang   thanks
